## Sigmoid

In [ ]:
import math

In [ ]:
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

In [ ]:
sigmoid(200)

1.0

In [ ]:
sigmoid(1)

0.7310585786300049

In [ ]:
sigmoid(-23)

1.0261879630648827e-10

In [ ]:
sigmoid(0.5)

0.6224593312018546

## tanh

In [ ]:
def tanh(x):
  return (math.exp(x) - math.exp(-x)) / (math.exp(x) + math.exp(-x))

In [ ]:
tanh(30)

1.0

In [ ]:
tanh(-30)

-1.0

In [ ]:
tanh(1)

0.7615941559557649

In [ ]:
tanh(0.5)

0.4621171572600098

## ReLU (Rectified Linear Unit)

In [ ]:
def relu(x):
  return max(0,x)

In [ ]:
relu(30)

30

In [ ]:
relu(-30)

0

In [ ]:
relu(1)

1

In [ ]:
relu(0.5)

0.5

## Leaky ReLU

In [ ]:
def leaky_relu(x):
  return max(0.1*x,x)

In [ ]:
leaky_relu(30)

30

In [ ]:
leaky_relu(-30)

-3.0

In [ ]:
leaky_relu(1)

1

In [ ]:
leaky_relu(0.5)

0.5

In [ ]:
leaky_relu(-0.5)

-0.05

## Activation Functions with PyTorch

In [3]:
import torch

In [10]:
print(torch.randn(4,4))

tensor([[-0.0486, -0.4529,  1.0933,  0.5512],
        [-0.8792,  1.1581,  1.7431, -0.9178],
        [ 0.0559, -0.5587,  2.7092,  0.3953],
        [ 0.0255,  0.7092,  0.0241, -0.3632]])


In [12]:
input_layer = torch.tensor([[-0.1109,  0.2522,  0.1926, -2.3325]]) # torch.randn(1, 4)
weight_1 = torch.tensor([[-0.0486, -0.4529,  1.0933,  0.5512], [-0.8792,  1.1581,  1.7431, -0.9178], [ 0.0559, -0.5587,  2.7092,  0.3953], [ 0.0255,  0.7092,  0.0241, -0.3632]])
weight_2 = torch.randn(4, 4)
weight_3 = torch.randn(4, 4)

In [13]:
hidden_1 = torch.matmul(input_layer, weight_1)
hidden_2 = torch.matmul(hidden_1, weight_2)

print(torch.matmul(hidden_2, weight_3))

tensor([[-0.5287,  3.4239,  0.5922, -2.7237]])


In [14]:
# Calculate weight_composed_1 and weight
weight_composed_1 = torch.matmul(weight_1, weight_2)
weight = torch.matmul(weight_composed_1, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

tensor([[-0.5287,  3.4239,  0.5922, -2.7237]])


Let's use ReLU

In [17]:
import torch.nn as nn

In [19]:
relu = nn.ReLU()

hidden_1_activated = relu(torch.matmul(input_layer, weight_1))
hidden_2_activated = relu(torch.matmul(hidden_1_activated, weight_2))
print(torch.matmul(hidden_2_activated, weight_3))

weight_composed_1_activated = relu(torch.matmul(weight_1, weight_2))

# Multiply `weight_composed_1_activated` with `weight_3
weight = torch.matmul(weight_composed_1_activated, weight_3)

# Multiply input_layer with weight
print(torch.matmul(input_layer, weight))

tensor([[-0.3159,  1.4455,  0.5784, -0.4004]])
tensor([[-1.7602,  1.6734,  1.4542, -1.9670]])


Matrix Calculation

In [27]:
# matmul
a = torch.tensor([1, 2])
b = torch.tensor([5, 6])

c = torch.tensor([[1, 2], [3, 4]])
d = torch.tensor([[5, 6], [7, 8]])

result1 = torch.matmul(a, b)
result2 = a * b

print(result1)
print(result2)

tensor(17)
tensor([ 5, 12])
