In [ ]:
import numpy as np

In [ ]:
true_value = np.array([1,0.5,0.3,0,0.7])
predicted_value = np.array([0,1,1,0,1])

## MAE (Mean Absolute Error)

In [ ]:
def mae(true_value, predicted_value):
  for t, p in zip(true_value, predicted_value):
    print(t, p)

In [ ]:
mae(true_value, predicted_value)

1.0 0
0.5 1
0.3 1
0.0 0
0.7 1


In [ ]:
def mae(true_value, predicted_value):
  total_error = 0
  for t, p in zip(true_value, predicted_value):
    total_error += abs(t - p)
  print("Total Error:", total_error)
  mae = total_error / len(true_value)
  print("MAE:", mae)

In [ ]:
mae(true_value, predicted_value)

Total Error: 2.5
MAE: 0.5


In [ ]:
predicted_value - true_value

array([-1. ,  0.5,  0.7,  0. ,  0.3])

In [ ]:
np.abs(predicted_value - true_value)

array([1. , 0.5, 0.7, 0. , 0.3])

In [ ]:
np.mean(np.abs(predicted_value - true_value))

0.5

## MSE (Mean Squared Error)

In [ ]:
def mse(true_value, predicted_value):
  total_error = 0
  for t, p in zip(true_value, predicted_value):
    total_error += (t - p)**2
  print("Total Squared Error:", total_error)
  mse = total_error/len(true_value)
  print("Mean Squared Error:", mse)

In [ ]:
mse(true_value, predicted_value)

Total Squared Error: 1.83
Mean Squared Error: 0.366


In [ ]:
np.square(true_value - predicted_value)

array([1.  , 0.25, 0.49, 0.  , 0.09])

In [ ]:
np.mean(np.square(true_value - predicted_value))

0.366

## Binary Cross Entropy (Log Loss)

In [ ]:
np.log(10)

2.302585092994046

In [ ]:
delta = 1e-15

In [ ]:
predicted_value

array([0, 1, 1, 0, 1])

In [ ]:
predicted_new = [max(i, delta) for i in predicted_value]
predicted_new

[1e-15, 1, 1, 1e-15, 1]

In [ ]:
predicted_new = [min(i, 1-delta) for i in predicted_new]
predicted_new

[1e-15, 0.999999999999999, 0.999999999999999, 1e-15, 0.999999999999999]

In [ ]:
predicted_new = np.array(predicted_new)

In [ ]:
-np.mean(true_value*np.log(predicted_new)+(1-true_value)*np.log(1-predicted_new))

17.2696280766844

In [ ]:
def log_loss(true_value, predicted_value):
  predicted_new = [max(i, delta) for i in predicted_value]
  predicted_new = [min(i, 1-delta) for i in predicted_new]
  predicted_new = np.array(predicted_new)
  return -np.mean(true_value*np.log(predicted_new)+(1-true_value)*np.log(1-predicted_new))

In [ ]:
log_loss(true_value, predicted_value)

17.2696280766844

## Loss Functions with PyTorch

In [ ]:
import torch
import torch.nn as nn

In [ ]:
# Initialize logits and ground truth
logits = torch.rand(1, 2000)
ground_truth = torch.tensor([123])

# Use cross-entropy loss
criterion = nn.CrossEntropyLoss()
#criterion = nn.L1Loss() # MAE
#criterion = nn.MSELoss() # MSE

# Calculate and print the loss
loss = criterion(logits, ground_truth)

In [ ]:
print(loss)

tensor(7.5246)
